import { ThemeProvider } from '@/components/theme-provider'
import TopBar from '@/components/top-bar'
import { Toaster } from '@/components/ui/sonner'
import '@/styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import localFont from 'next/font/local'

// Font files can be colocated inside of `pages`
const cooperBlack = localFont({ src: '../styles/fonts/COOPBL.woff' })

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${cooperBlack.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <main
              className={`${cooperBlack.className} justify-center h-screen`}
            >
              <TopBar />
              {children}
              <Toaster />
            </main>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
