import { ThemeProvider } from '@/components/theme-provider'
import TopBar from '@/components/top-bar'
import '@/styles/globals.css'
import { ClerkProvider } from '@clerk/nextjs'

import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <main
              className={`font-sans ${inter.variable} justify-center h-screen`}
            >
              <TopBar authed={true} />
              <div className="flex items-center justify-center">
                <div className="w-full h-full p-6 md:max-w-7xl">
                  {children}
                  {/* <Toaster /> */}
                </div>
              </div>
            </main>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
